#!/bin/bash
set -Eeuo pipefail

# Dedicated KWin builder for WinLite. Unlike the normal KDE RootFS path this
# package is not a desktop compositor distribution: it only keeps the pieces
# required to bridge Droidspaces/AnLand to Xwayland/Wine.

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
MI_PAD4_DIR="$(cd "$SCRIPT_DIR/.." && pwd)"
BUILD_ROOT="${WINLITE_KWIN_BUILD_ROOT:-/tmp/droidspaces-winlite-kwin}"
OUTPUT_DIR="${ANLAND_PACKAGE_OUTPUT_DIR:-/out}"
KWINKG="${KWINKG:-365ae0acc5f521f53a85fe6d9a030646687324f8}"

trap 'rc=$?; echo "WinLite bridge-only KWin build failed: ${BASH_COMMAND} (exit ${rc})" >&2; exit "$rc"' ERR

pacman -S --noconfirm --needed \
    base-devel cmake git ninja meson extra-cmake-modules \
    plasma-wayland-protocols python qt6-tools vulkan-headers wayland-protocols \
    xorgproto xtrans xorg-font-util xorg-xwayland libcap sudo

if ! id user >/dev/null 2>&1; then
    useradd -m -s /bin/bash user
fi
install -d -m 0755 /etc/sudoers.d
printf '%s\n' 'user ALL=(ALL) NOPASSWD: ALL' >/etc/sudoers.d/droidspaces-user
chmod 0440 /etc/sudoers.d/droidspaces-user

rm -rf "$BUILD_ROOT"
mkdir -p "$BUILD_ROOT/packages"

dir="$BUILD_ROOT/kwin"
git clone --filter=blob:none --no-checkout \
    https://gitlab.archlinux.org/archlinux/packaging/packages/kwin.git "$dir"
git -C "$dir" fetch --depth=1 origin "$KWINKG"
git -C "$dir" checkout --detach "$KWINKG"
sed -i "s/^arch=(.*)$/arch=('aarch64')/" "$dir/PKGBUILD"

# These dependencies belong to desktop/KCM/effect/shortcut integrations that
# are compiled out below. Keeping them in .PKGINFO would cause pacman to pull a
# large part of Plasma/KIO back into an otherwise minimal WinLite image.
drop_deps=(
    aurorae
    breeze
    iio-sensor-proxy
    kcmutils
    kdeclarative
    kglobalacceld
    kirigami
    kitemmodels
    knewstuff
    knotifications
    kquickcharts
    kscreenlocker
    kxmlgui
    libei
    libplasma
    libqaccessibilityclient-qt6
    milou
    plasma-activities
    kdoctools
    krunner
)
for dep in "${drop_deps[@]}"; do
    sed -Ei "/^[[:space:]]*['\"]${dep}([<>=][^'\"]*)?['\"]([[:space:]]*#.*)?$/d" "$dir/PKGBUILD"
done

# Fail loudly if Arch changes the PKGBUILD layout and a dependency we intended
# to remove is still present. Silent dependency drift defeats the size target.
for dep in "${drop_deps[@]}"; do
    if grep -Eq "['\"]${dep}([<>=][^'\"]*)?['\"]" "$dir/PKGBUILD"; then
        echo "WinLite dependency pruning missed: $dep" >&2
        grep -nE "['\"]${dep}([<>=][^'\"]*)?['\"]" "$dir/PKGBUILD" >&2 || true
        exit 1
    fi
done

cp "$MI_PAD4_DIR/anland-kwin/kwin.patch" "$dir/anland-kwin.patch"
cp -a "$MI_PAD4_DIR/anland-kwin/backend" "$dir/anland-backend"

cat >>"$dir/PKGBUILD" <<'EOF_WINLITE_KWIN'
source+=(anland-kwin.patch)
sha256sums+=('SKIP')

prepare() {
  cd "$srcdir/kwin-$pkgver"
  patch -Np1 -i "$srcdir/anland-kwin.patch"
  mkdir -p src/backends/anland
  cp -a "$startdir/anland-backend/." src/backends/anland/

  # Pre-seed CMake before its option() declarations. This keeps only the Wayland
  # compositor + Xwayland path that Wine needs; all desktop-facing integrations
  # are compiled out instead of merely being disabled at runtime.
  python3 - CMakeLists.txt <<'PY_WINLITE_CMAKE'
from pathlib import Path
import sys

path = Path(sys.argv[1])
text = path.read_text()
marker = 'project(KWin VERSION ${PROJECT_VERSION})'
if text.count(marker) != 1:
    raise SystemExit('unexpected KWin CMakeLists project marker')

flags = [
    'BUILD_TESTING',
    'KWIN_BUILD_ACTIVITIES',
    'KWIN_BUILD_DECORATIONS',
    'KWIN_BUILD_EIS',
    'KWIN_BUILD_GLOBALSHORTCUTS',
    'KWIN_BUILD_KCMS',
    'KWIN_BUILD_NOTIFICATIONS',
    'KWIN_BUILD_RUNNERS',
    'KWIN_BUILD_SCREENLOCKER',
    'KWIN_BUILD_TABBOX',
    'KWIN_BUILD_X11_BACKEND',
]
block = ['','## WinLite bridge-only build: generated by build-kwin-bridge.sh']
block += [f'set({name} OFF CACHE BOOL "WinLite bridge-only" FORCE)' for name in flags]
block += [
    'set(KWIN_BUILD_X11 ON CACHE BOOL "Wine Xwayland support" FORCE)',
    'set(CMAKE_DISABLE_FIND_PACKAGE_KF6DocTools TRUE CACHE BOOL "WinLite no docs" FORCE)',
    'set(CMAKE_DISABLE_FIND_PACKAGE_KF6Kirigami TRUE CACHE BOOL "WinLite no QML desktop effects" FORCE)',
    'set(CMAKE_DISABLE_FIND_PACKAGE_Plasma TRUE CACHE BOOL "WinLite no Plasma runtime" FORCE)',
    'set(CMAKE_DISABLE_FIND_PACKAGE_PlasmaActivities TRUE CACHE BOOL "WinLite no activities" FORCE)',
    'set(CMAKE_DISABLE_FIND_PACKAGE_QAccessibilityClient6 TRUE CACHE BOOL "WinLite no accessibility desktop integration" FORCE)',
    '',
]
text = text.replace(marker, marker + '\n' + '\n'.join(block), 1)
path.write_text(text)
PY_WINLITE_CMAKE

  grep -Fq 'set(KWIN_BUILD_SCREENLOCKER OFF CACHE BOOL "WinLite bridge-only" FORCE)' CMakeLists.txt
  grep -Fq 'set(KWIN_BUILD_GLOBALSHORTCUTS OFF CACHE BOOL "WinLite bridge-only" FORCE)' CMakeLists.txt
  grep -Fq 'set(KWIN_BUILD_X11 ON CACHE BOOL "Wine Xwayland support" FORCE)' CMakeLists.txt
}
EOF_WINLITE_KWIN

chown -R user:user "$BUILD_ROOT"
su user -c "cd '$dir' && PKGDEST='$BUILD_ROOT/packages' makepkg --syncdeps --noconfirm --nocheck --skippgpcheck --cleanbuild --clean"

package="$(find "$BUILD_ROOT/packages" -maxdepth 1 -type f -name 'kwin-[0-9]*.pkg.tar.*' -print -quit)"
[[ -n "$package" ]] || {
    echo 'bridge-only kwin package was not produced' >&2
    find "$BUILD_ROOT" -maxdepth 3 -type f -name '*.pkg.tar.*' -print >&2 || true
    exit 1
}

pkginfo="$BUILD_ROOT/kwin.PKGINFO"
bsdtar -xOf "$package" .PKGINFO >"$pkginfo"
grep -Eq '^pkgname = kwin$' "$pkginfo"
bsdtar -tf "$package" | grep -Eq '(^|/)usr/bin/kwin_wayland$'

for dep in "${drop_deps[@]}"; do
    if grep -Eq "^depend = ${dep}([<>=].*)?$" "$pkginfo"; then
        echo "bridge-only KWin still declares unwanted dependency: $dep" >&2
        exit 1
    fi
done
if grep -Eq '^depend = kio([<>=].*)?$' "$pkginfo"; then
    echo 'bridge-only KWin unexpectedly depends directly on KIO' >&2
    exit 1
fi

mkdir -p "$OUTPUT_DIR"
cp -v "$package" "$OUTPUT_DIR/"
printf '%s\n' \
    'profile=winlite-bridge-only' \
    'xwayland=enabled' \
    'x11-backend=disabled' \
    'decorations=disabled' \
    'kcms=disabled' \
    'notifications=disabled' \
    'global-shortcuts=disabled' \
    'runners=disabled' \
    'activities=disabled' \
    'eis=disabled' \
    'screenlocker=disabled' \
    >"$OUTPUT_DIR/WINLITE-KWIN-PROFILE"

printf 'bridge-only-package='; basename "$package"
printf 'package-bytes='; stat -c %s "$package"
echo 'WinLite bridge-only KWin package built successfully'
