panels=panel1

[panel1]
plugins=mainmenu,taskbar,tray,volume,worldclock
position=Bottom
desktop=0
height=30
iconSize=20
reserve-space=true

[mainmenu]
type=mainmenu
alignment=Left

[taskbar]
type=taskbar
buttonWidth=140
closeOnMiddleClick=true
groupingEnabled=true
showOnlyCurrentDesktopTasks=false

[tray]
type=tray
alignment=Right

[volume]
type=volume
alignment=Right

[worldclock]
type=worldclock
alignment=Right
timeFormat=HH:mm
