panels=panel1

[panel1]
plugins=fancymenu,quicklaunch,taskbar,tray,volume,worldclock
position=Bottom
desktop=0
height=42
iconSize=28
reserve-space=true

[fancymenu]
type=fancymenu
alignment=Left
filterClear=true
autoSel=true
autoSelDelay=120

[quicklaunch]
type=quicklaunch
alignment=Left
apps=pcmanfm-qt.desktop,foot.desktop,winecfg.desktop

[taskbar]
type=taskbar
buttonWidth=180
closeOnMiddleClick=true
groupingEnabled=true
showOnlyCurrentDesktopTasks=false

[tray]
type=tray
alignment=Right

[volume]
type=volume
alignment=Right

[worldclock]
type=worldclock
alignment=Right
timeFormat=hh:mm
dateFormat=yyyy-MM-dd
