[Behavior]
ConfirmDelete=true
SingleClick=false

[Desktop]
ShowTrash=false
WallpaperMode=stretch

[FolderView]
Mode=icon
ShowHidden=false
SortColumn=name
SortOrder=ascending

[System]
FallbackIconThemeName=breeze

[Thumbnail]
MaxExternalThumbnailFileSize=0
ShowThumbnails=false
