#!/bin/bash

set -u

unset LIBGL_ALWAYS_SOFTWARE QT_QUICK_BACKEND QT_OPENGL GALLIUM_DRIVER
export MESA_LOADER_DRIVER_OVERRIDE=kgsl
export FD_FORCE_KGSL=1
export FD_KGSL_ENABLE_DMABUF=1
export XWAYLAND_FORCE_KGSL_SURFACELESS=1
export KWIN_DISABLE_VULKAN=1
export LD_PRELOAD=/usr/local/lib/libion-legacy-shim.so

exec /usr/sbin/kwin_wayland --anland "$@"
