[System]
IconThemeName=breeze
FallbackIconThemeName=hicolor
Archiver=ark
Terminal=konsole
SIUnit=false

[Behavior]
BookmarkOpenMethod=0
SingleWindowMode=true
UseTrash=true
SingleClick=true
ConfirmDelete=true

[Volume]
MountOnStartup=false
MountRemovable=false
AutoRun=false

[FolderView]
Mode=icon
ShowHidden=false
SortOrder=ascending
SortColumn=name
BigIconSize=40
SmallIconSize=22
SidePaneIconSize=22
ThumbnailIconSize=64

[Window]
FixedHeight=700
FixedWidth=1100
LastWindowHeight=700
LastWindowWidth=1100
RememberWindowSize=true
AlwaysShowTabs=false
ShowTabClose=true
SplitterPos=220
SidePaneMode=0

[Thumbnail]
ShowThumbnails=false
MaxThumbnailFileSize=0
ThumbnailLocalFilesOnly=true
